plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'springweb'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies { // start.spring.io
	// 의존성( dependencies ) { } 안에 프로젝트내 추가할 라이브러리 코드 -> 자동으로 라이브러리 설치
	// 1. springboot
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	// 2. MYSQL jdbc
	runtimeOnly 'com.mysql:mysql-connector-j'
	// 3. 롬복 
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// 4. JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // 5. HTTP 통신
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	// 6. XML 파싱
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.22.2'
	// 7. CSV 파싱
	implementation 'com.opencsv:opencsv:5.12.0'
	// 8. 비크립트 관련 라이브러리 설치
	implementation 'org.springframework.security:spring-security-crypto'
	// 9. JWT 관련 의존성 추가
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
   	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
   	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	// 10.  implementation 'org.springframework.ai:spring-ai-starter-vector-store-redis'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	// 11. web socket
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	
}

tasks.named('test') {
	useJUnitPlatform()
}
