spring.application.name=springweb
# 주석 : .properties 파일의 주석 방법
# application.properties 파일이란? spring 관련 설정 코드 입력하는 곳
# 1. 내장 톰캣의 포트 번호 변경 , 기본값이 8080
server.port = 8080
# 2. 데이터베이스 연동
# 2-1 : 연동할 DB 주소
spring.datasource.url = jdbc:mysql://localhost:3306/mydb0903
# 2-2 : DB 주소의 계정명/비밀번호
spring.datasource.username=root
spring.datasource.password=1234
# 2-3 Entity 테이블 생성/수정  , DDL : sql정의어 *개발단계* 디버깅(확인용) *운영/배포 단계 사용하지 않는다*
# create : 서버실행할때마다 삭제후 생성
# update : 서버실행할때마다 존재하면 수정 존재하지 않으면 생성
# none : 사용안함.
spring.jpa.hibernate.ddl-auto = create-drop

# 1. JPA가 생성한 SQL 콘솔 출력 (표준 stdout 출력)
spring.jpa.show-sql=true
# 2. 콘솔에 출력되는 SQL 줄바꿈 및 들여쓰기 적용 (가독성 향상)
spring.jpa.properties.hibernate.format_sql=true
# 3. SQL 실행 쿼리 로깅 (Logger 레벨 설정)
logging.level.org.hibernate.sql=DEBUG
# 4. SQL 내부의 파라미터 바인딩 값(?에 들어간 실제 값)을 콘솔에 출력 (디버깅 핵심)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# 5 서버 실행 할때 SQL 파일 실행 *개발단계* , always,none *운영/배포 단계 사용하지 않는다*
spring.sql.init.mode = always
# 6 서버 실행 할때 classpath(resources폴더) 이하 에 data.sql 파일 경로 지정
spring.sql.init.data-locations=classpath:/sql/0903.sql
# 7 서버 실행 할때 JPA가 초기화 파일 실행
spring.jpa.defer-datasource-initialization = true
# 8. SQL 파일 한글 인코딩
spring.sql.init.encoding=UTF-8