spring.application.name=springweb
# 주석 : .properties 파일의 주석 방법
# application.properties 파일이란? spring 관련 설정 코드 입력하는곳 
# 1. 내장 톰캣의 포트 번호 변경 , 기본값이 8080 
server.port = 8080
# 2. 데이터베이스연동
# 2-1:연동할 DB 주소 
# spring.datasource.url = jdbc:mysql://localhost:3306/mydb0902
# spring.datasource.url = jdbc:mysql://localhost:3306/mydb0903
# spring.datasource.url = jdbc:mysql://localhost:3306/practice3
# spring.datasource.url = jdbc:mysql://localhost:3306/practice4
# spring.datasource.url = jdbc:mysql://localhost:3306/practice5
# spring.datasource.url = jdbc:mysql://localhost:3306/mydb0923
#spring.datasource.url = jdbc:mysql://localhost:3306/mydb0928
spring.datasource.url = jdbc:mysql://localhost:3306/mydb1002

# 2-2:DB주소의 계정명/비밀번호
spring.datasource.username=root
spring.datasource.password=1234

# 3. DDL
# create : 서버 실행될때 엔티티 기반으로 테이블 삭제->생성
# create-drop: 서버 실행될때 엔티티 기반으로 테이블 생성 , 서버 종료시 삭제
# update : 서버 실행될 때 존재하면 엔티티 수정 없으면 생성
# none : 사용안함 
spring.jpa.hibernate.ddl-auto=create-drop

# 4. 콘솔에서 SQL 출력
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 5. 서버 실행될 때 (DML) data.sql (경로) 파일 실행 , classpath(resources폴더):
#spring.sql.init.data-locations=classpath:/sql/0903.sql
#spring.sql.init.data-locations=classpath:/sql/practice3.sql
#spring.sql.init.data-locations=classpath:/sql/practice4.sql
# spring.sql.init.data-locations=classpath:/sql/practice5.sql
#spring.sql.init.data-locations=classpath:/sql/practice6.sql
# spring.sql.init.data-locations=classpath:/sql/0923.sql
# spring.sql.init.data-locations=classpath:/sql/0928.sql
spring.sql.init.data-locations=classpath:/sql/1002.sql
spring.sql.init.mode = always
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization = true

# 6. 외부 api 서비스키
# 6-1: 공공데이터 key
api.public-data.service-key=

# 7. JWT 비밀키
# 마음대로 32글자 임의 데이터(32바이트) # 임의로 12345678 4번 
jwt.secret=12345678123456781234567812345678


# 8. 레디스 연동 
spring.data.redis.host=localhost
spring.data.redis.port=6379