-- Active: 1789713930507@@127.0.0.1@3306@board
INSERT INTO board (title, content, file_name, create_date, update_date) VALUES
('첫 번째 공지사항', '게시판 서비스 오픈을 환영합니다.', NULL, NOW(), NOW()),
('스프링 부트 파일 업로드 가이드', 'MultipartFile을 활용한 첨부파일 업로드 안내입니다.', NULL, NOW(), NOW()),
('리액트 라우터 연동 테스트', 'React Router와 Axios를 이용한 상세 조회 및 다운로드 테스트 글입니다.', NULL, NOW(), NOW()),
('시스템 점검 안내', '금일 자정 시스템 정기 점검이 진행될 예정입니다.', NULL, NOW(), NOW()),
('JPA Auditing 기능 소개', 'BaseTime 클래스를 상속받아 생성일시와 수정일시를 자동으로 관리합니다.', NULL, NOW(), NOW()),
('RESTful API 설계 표준 안내', '컨트롤러 및 서비스 계층 분리 원칙과 DTO 설계 가이드라인입니다.', NULL, NOW(), NOW()),
('자유게시판 이용 수칙', '게시판 이용 시 비방이나 욕설은 제재 대상이 될 수 있습니다.', NULL, NOW(), NOW()),
('서버 아키텍처 다이어그램', 'Spring Boot와 React 간의 비동기 통신 흐름 다이어그램입니다.', NULL, NOW(), NOW()),
('DB 커넥션 풀 설정 팁', 'HikariCP 옵션 튜닝을 통한 커넥션 누수 방지 팁을 공유합니다.', NULL, NOW(), NOW()),
('테스트 게시물 10번', '페이징 및 무한 스크롤 테스트를 위한 10번째 샘플 레코드입니다.', NULL, NOW(), NOW()),
('웹 보안 기초: CORS 이해하기', '교차 출처 리소스 공유(CORS) 설정과 브라우저 보안 정책 정리입니다.', NULL, NOW(), NOW()),
('Spring Data JPA 페이징 처리법', 'Pageable 인터페이스를 활용한 PageRequest 및 Slice 처리 가이드입니다.', NULL, NOW(), NOW()),
('React 상태 관리 팁', 'useState와 useEffect 사용 시 주의해야 할 렌더링 사이클 정리입니다.', NULL, NOW(), NOW()),
('FormData 전송 시 주의점', 'Multipart 파일과 JSON 데이터를 함께 전송할 때 발생하는 이슈 해결법입니다.', NULL, NOW(), NOW()),
('HTTP 응답 상태 코드 정리', '200, 201, 400, 404, 500 등 실무에서 주로 쓰는 상태 코드 기준입니다.', NULL, NOW(), NOW()),
('데이터베이스 인덱스 설계 기초', 'B-Tree 인덱스 구조와 조회 성능 최적화를 위한 컬럼 선택 기준입니다.', NULL, NOW(), NOW()),
('비동기 처리: async/await 활용법', 'Promise 체이닝 대비 가독성 향상과 에러 핸들링 패턴입니다.', NULL, NOW(), NOW()),
('Lombok 어노테이션 활용 팁', '@RequiredArgsConstructor와 @Builder의 올바른 사용법입니다.', NULL, NOW(), NOW()),
('UUID를 이용한 파일명 난수화', '중복 방지 및 파일 경로 보안을 위한 UUID 적용 방식 설명입니다.', NULL, NOW(), NOW()),
('엔티티와 DTO 분리 이유', '영속성 컨텍스트 보호와 API 스펙 변화에 유연하게 대응하는 방법입니다.', NULL, NOW(), NOW()),
('트랜잭션 격리 수준 안내', 'ACID 원칙과 격리 수준(Read Committed 등)의 개념입니다.', NULL, NOW(), NOW()),
('웹 브라우저 렌더링 파이프라인', 'DOM 트리 구성부터 렌더 트리, 레이아웃, 페인팅 과정 정리입니다.', NULL, NOW(), NOW()),
('로그 관리 전략: SLF4J', '운영 환경에서 System.out 대신 로깅 프레임워크를 써야 하는 이유입니다.', NULL, NOW(), NOW()),
('클라우드 스토리지 연동 개념', '로컬 디렉토리 저장 대신 AWS S3/GCS를 연동하는 표준 구조입니다.', NULL, NOW(), NOW()),
('PathVariable vs RequestParam', 'RESTful URL 설계 시 파라미터 전달 방식의 차이점입니다.', NULL, NOW(), NOW()),
('객체 지향 설계 5대 원칙 SOLID', '단일 책임 원칙(SRP)과 의존역전 원칙(DIP) 중심의 설계 요령입니다.', NULL, NOW(), NOW()),
('JVM 가비지 컬렉션(GC) 기초', 'Heap 메모리 영역 분할과 세대별 가비지 컬렉터의 동작 방식입니다.', NULL, NOW(), NOW()),
('JWT 기반 인증 흐름 개요', 'Access Token과 Refresh Token을 활용한 무상태 인증 구조입니다.', NULL, NOW(), NOW()),
('Git 브랜치 전략 정리', 'Git-Flow와 GitHub-Flow의 차이 및 실무 협업 브랜치 운용법입니다.', NULL, NOW(), NOW()),
('30번째 게시물 테스트', '게시판 30개 샘플 데이터 삽입 및 목록 페이징 검증용 레코드입니다.', NULL, NOW(), NOW());